spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:antessio_event_sourcing}
    username: ${DB_USERNAME:event_sourcing_user}
    password: ${DB_PASSWORD:event_sourcing_password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true